### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Sreyan88** [Exgc/AVMuST-TED#1]
Hi,

Awesome paper! When will the dataset be available for download?

**Comment by Exgc** [comment]
Thank you for your interest in our work. We will release the dataset in early February, so stay tuned.

**Comment by Sreyan88** [comment]
and do you plan on releasing the code too?

**Comment by Exgc** [comment]
We plan to share the code in the near future. However, due to our current engagement in completing another task under a tight schedule, we kindly request your patience for a little more time.

**Comment by Exgc** [comment]
The download link of AVMuST-TED has been updated.
